FROM ubuntu:latest

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update --fix-missing -qq && apt-get install -y -q \
    mafft \
    python3 \
    python3-pip \
    curl \
    wget \
    git-core \
    bzip2 \
    pypy \
    libncurses5-dev  \
    libncursesw5-dev \
    build-essential \
    pkg-config \
    zlib1g-dev \
    default-jre \
    && apt-get clean \
    && apt-get purge

# Install networkx
RUN python3 -m pip install GenGraph numpy matplotlib biopython pandas

# Install a MSA tool
# Muscle

RUN curl -fksSL http://drive5.com/muscle/downloads3.8.31/muscle3.8.31_i86linux64.tar.gz | tar xz && \
    mv muscle3.8.31_i86linux64 /usr/local/bin/muscle3.8.31_i86darwin64

# Install MAUVE

RUN curl -fksSL http://darlinglab.org/mauve/snapshots/2015/2015-02-13/linux-x64/mauve_linux_snapshot_2015-02-13.tar.gz | tar xz && \
    cp mauve_snapshot_2015-02-13/linux-x64/progressiveMauve /usr/local/bin/

#CMD echo "This is where we run GG toolkit"

RUN python3 -m pip install networkx

RUN git clone --branch networkx_2_4_fixes https://github.com/jambler24/GenGraph

ENTRYPOINT ["python3", "./GenGraph/gengraphTool.py"]

CMD ["-h"]

# Build this image
#docker build -t ggimage -f DockerFile .
