FROM ubuntu:latest

RUN apt-get update --fix-missing -qq && apt-get install -y -q \
    python3 \
    python3-pip \
    python-pip \
    curl \
    wget \
    git-core \
    bzip2 \
    libncurses5-dev  \
    libncursesw5-dev \
    build-essential \
    pkg-config \
    zlib1g-dev \
    default-jre \
    && apt-get clean \
    && apt-get purge

# Install networkx
RUN pip install networkx

# Install a MSA tool
# Muscle

RUN curl -fksSL http://drive5.com/muscle/downloads3.8.31/muscle3.8.31_i86linux64.tar.gz | tar xz && \
    mv muscle3.8.31_i86linux64 /usr/local/bin/muscle3.8.31_i86darwin64


# Install MAUVE

RUN curl -fksSL http://darlinglab.org/mauve/snapshots/2015/2015-02-13/linux-x64/mauve_linux_snapshot_2015-02-13.tar.gz | tar xz && \
    cp mauve_snapshot_2015-02-13/linux-x64/progressiveMauve /usr/local/bin/
